EREGCSC-336 guidance download
CMSgov/cmcs-eregulations pull request #46
Opened 2021-03-11 18:21 UTC by theabrad

2021-03-12 13:14 UTC, whytheplatypus requested changes
looking really good. I tried it out locally and the new guidance loaded and looks great. Couple ideas on making the errors more helpful.

2021-03-12 13:14 UTC, whytheplatypus commented on guidance_pipeline/main.go
> +	if flag.NFlag() == 0 {
Needs a way to check explicitly for `file`, `directory`, or `url`. This passes if only `-o` is provided.

2021-03-12 13:14 UTC, whytheplatypus commented on guidance_pipeline/main.go
> +		filename := formatFilename(*outputDirectory, key)
Give more context in the error states by adding things like this filename. Things like `fmt.Errorf("%s %s", filename, err)` work or a special Error type if it makes sense.

2021-03-12 20:41 UTC, theabrad commented
check if valid URL in the link section and log if not.

2021-03-16 12:40 UTC, whytheplatypus requested changes

2021-03-16 12:40 UTC, whytheplatypus commented on guidance_pipeline/main.go
> +					Link: validURL(header, record[1]),
To prevent the user seeing broken links this should return an error and not get added to `guidance` if it is an invalid url.

2021-03-17 12:28 UTC, whytheplatypus approved these changes

2021-03-17 14:56 UTC, merged