EREGCSC-1712 API endpoint for retrieving a list of valid years for GovInfo display
CMSgov/cmcs-eregulations pull request #674
Opened 2023-01-24 18:27 UTC by cgodwin1

Resolves #1712

**Description-**

This endpoint takes a title, part, and section combination and queries GovInfo's link service to determine which years have valid historical PDFs associated with them.

**This pull request changes...**

- New endpoint exists, `/v3/title/<title>/part/<part>/history/section/<section>`.
- Endpoint returns a list of valid years and links to PDF versions of the reg for that year.
- Queries are performed asynchronously which should be fine as the number of requests (per request) is small.

**Steps to manually verify this change...**

1. Visit `/v3/title/<title>/part/<part>/history/section/<section>` and plug in valid values like `title=42`, `part=433`, `section=50`.
2. Verify the data returned is returned quickly, and contains valid years and PDF links.

2023-01-25 14:27 UTC, thwalker6 requested changes

2023-01-25 15:55 UTC, cgodwin1 commented on solution/backend/regcore/tests/test_api_view.py
> +    def test_get_historical_sections(self):
Do you know how to mock it? Was looking it up but I ran out of time yesterday.

2023-01-25 16:03 UTC, cgodwin1 commented on solution/backend/regcore/tests/test_api_view.py
> +    def test_get_historical_sections(self):
Doesn't seem to be a way to do it without introducing yet more dependencies.

2023-01-25 16:31 UTC, thwalker6 commented on solution/backend/regcore/tests/test_api_view.py
> +    def test_get_historical_sections(self):
Its not hard to mock.  You need to use patching in the unittest to say "if this url is called return this instead."  there are a couple of ways to do it

2023-01-25 20:02 UTC, cgodwin1 commented on solution/backend/regcore/tests/test_api_view.py
> +    def test_get_historical_sections(self):
Resolved as of [8565ebb](https://github.com/CMSgov/cmcs-eregulations/pull/674/commits/8565ebbefebbdd1b0f7881fa3c5c410e43aa0e74)

2023-01-25 20:18 UTC, thwalker6 approved these changes
lgtm.

2023-01-26 15:06 UTC, PhilR8 approved these changes
Response looks great!  LGTM!

2023-01-26 15:07 UTC, merged